import { assertJobEligible } from '../../_lib/build-plan-state.mjs';
import { lintPlan, sourceSnapshot } from '../../_lib/build-plan-rules.mjs';
import { isGeneralJob, validateGeneralJobUpdate, validateNewGeneralJob } from '../_lib/general-jobs.mjs';
import { ensureJobsSchema } from '../_lib/jobs-schema.mjs';

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'private, no-store'}});}
async function ensureSchema(db){await ensureJobsSchema(db);await db.batch([
  db.prepare(`CREATE TABLE IF NOT EXISTS job_build_plan_events (id INTEGER PRIMARY KEY AUTOINCREMENT,job_id TEXT NOT NULL,quote_id TEXT,plan_version INTEGER,knowledge_version TEXT,event_type TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL DEFAULT 'mark',notes TEXT)`),
  db.prepare(`CREATE INDEX IF NOT EXISTS idx_job_build_plan_events_job ON job_build_plan_events(job_id,created_at DESC)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS job_closeouts (id INTEGER PRIMARY KEY AUTOINCREMENT,job_id TEXT NOT NULL UNIQUE,walkthrough_confirmed INTEGER NOT NULL DEFAULT 0,warranty_handoff_confirmed INTEGER NOT NULL DEFAULT 0,balance_confirmed INTEGER NOT NULL DEFAULT 0,signoff_name TEXT NOT NULL DEFAULT '',signoff_notes TEXT NOT NULL DEFAULT '',finalized_at TEXT,updated_at TEXT NOT NULL,updated_by TEXT NOT NULL DEFAULT 'mark')`),
  db.prepare(`CREATE INDEX IF NOT EXISTS idx_job_closeouts_job ON job_closeouts(job_id)`),
]);}
function makeId(){return `J-${new Date().toISOString().slice(0,10).replace(/-/g,'')}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;}
function parsePlan(row){if(!row?.build_plan_json)return null;try{return JSON.parse(row.build_plan_json);}catch{return null;}}
function sameSource(a,b){return JSON.stringify(a||[])===JSON.stringify(b||[]);}
async function checklistProgress(db,jobId){try{const r=await db.prepare(`SELECT COUNT(*) AS total,SUM(CASE WHEN checked=1 THEN 1 ELSE 0 END) AS done FROM job_checklist_items WHERE job_id = ?`).bind(jobId).first();return {total:Number(r?.total||0),done:Number(r?.done||0)};}catch{return {total:0,done:0};}}
async function validatedApprovedPlan(db,quoteId){const quote=await db.prepare(`SELECT * FROM quotes WHERE id = ?`).bind(quoteId).first();if(!quote)return{error:'Quote not found.',status:404};if(quote.status!=='finalized')return{error:'Only finalized quotes can provide a production snapshot.',status:409};const{results:items}=await db.prepare(`SELECT * FROM quote_items WHERE quote_id = ? ORDER BY sort_order ASC,id ASC`).bind(quoteId).all();const currentSource=sourceSnapshot(items);const savedPlanRow=await db.prepare(`SELECT * FROM quote_build_plans WHERE quote_id = ?`).bind(quoteId).first();if(!savedPlanRow?.plan_json)return{error:'An approved Build Plan is required before this snapshot can be attached.',code:'BUILD_PLAN_REQUIRED',status:409};if(savedPlanRow.state!=='approved')return{error:'The Build Plan must be explicitly approved before this snapshot can be attached.',code:'BUILD_PLAN_NOT_APPROVED',status:409};if(!savedPlanRow.approved_at||!savedPlanRow.updated_at||new Date(savedPlanRow.updated_at).getTime()>new Date(savedPlanRow.approved_at).getTime())return{error:'The Build Plan was changed after approval. Re-review and approve the current version first.',code:'BUILD_PLAN_CHANGED_AFTER_APPROVAL',status:409};let plan=null;try{plan=JSON.parse(savedPlanRow.plan_json);}catch{}if(!plan)return{error:'The saved Build Plan is invalid.',code:'BUILD_PLAN_INVALID',status:409};if(!sameSource(plan.sourceItems,currentSource))return{error:'The quote changed after Build Plan approval. Regenerate, review and approve the plan again before attaching it.',code:'BUILD_PLAN_STALE',status:409};const quality=lintPlan(plan,items);plan.quality=quality;try{assertJobEligible({...plan,status:savedPlanRow.state,quality});}catch(error){return{error:error.message,code:'BUILD_PLAN_BLOCKED',blockers:quality.blockers,warnings:quality.warnings,status:409};}return{quote,items,plan,savedPlanRow,planVersion:Number(savedPlanRow.version||1),knowledgeVersion:savedPlanRow.knowledge_version||plan?.knowledgeVersion||null};}
export async function onRequestGet(context){const{env}=context;await ensureSchema(env.QUOTES_DB);const url=new URL(context.request.url),id=url.searchParams.get('id');if(id){const job=await env.QUOTES_DB.prepare(`SELECT * FROM jobs WHERE id = ?`).bind(id).first();if(!job)return json({error:'Job not found.'},404);let quote=null,items=[];if(job.quote_id){quote=await env.QUOTES_DB.prepare(`SELECT * FROM quotes WHERE id = ?`).bind(job.quote_id).first();if(quote){const result=await env.QUOTES_DB.prepare(`SELECT * FROM quote_items WHERE quote_id = ? ORDER BY sort_order ASC,id ASC`).bind(job.quote_id).all();items=result.results||[];}}return json({job,quote,items,buildPlan:parsePlan(job),buildPlanVersion:Number(job.build_plan_version||0),buildPlanKnowledgeVersion:job.build_plan_knowledge_version||null,buildPlanAttachedAt:job.build_plan_attached_at||null,buildPlanAttachedBy:job.build_plan_attached_by||null,checklist:await checklistProgress(env.QUOTES_DB,id)});}const limit=200,page=Math.max(1,Number.parseInt(url.searchParams.get('page')||'1',10)||1),offset=(page-1)*limit;
  const status=url.searchParams.get('status');
  if(status&&!['ready','scheduled','in-progress','completed','cancelled'].includes(status))return json({error:'Choose a valid job status.'},400);
  const conditions=[],bindings=[];
  if(status){conditions.push('j.status = ?');bindings.push(status);}
  const from=url.searchParams.get('from'),to=url.searchParams.get('to');
  if(from!==null||to!==null){
    const valid=(value)=>typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(Date.parse(`${value}T12:00:00Z`))&&new Date(`${value}T12:00:00Z`).toISOString().slice(0,10)===value;
    if(!valid(from)||!valid(to)||from>=to||Date.parse(to)-Date.parse(from)>31*86400000)return json({error:'Choose a valid schedule range of 1 to 31 days.'},400);
    conditions.push("j.scheduled_date >= ? AND j.scheduled_date < ? AND j.status <> 'cancelled'");bindings.push(from,to);
  }
  const where=conditions.length?`WHERE ${conditions.join(' AND ')}`:'';
  const [rows,totalRow,activeRow]=await Promise.all([
    env.QUOTES_DB.prepare(`SELECT j.*,COALESCE(q.total_cents,j.agreed_cents) AS total_cents FROM jobs j LEFT JOIN quotes q ON q.id=j.quote_id ${where} ORDER BY CASE j.status WHEN 'scheduled' THEN 0 WHEN 'ready' THEN 1 WHEN 'in-progress' THEN 2 WHEN 'completed' THEN 3 ELSE 4 END,COALESCE(j.scheduled_date,'9999-12-31') ASC,j.created_at DESC,j.id ASC LIMIT ? OFFSET ?`).bind(...bindings,limit,offset).all(),
    env.QUOTES_DB.prepare(`SELECT COUNT(*) AS total FROM jobs j ${where}`).bind(...bindings).first(),
    env.QUOTES_DB.prepare(`SELECT COUNT(*) AS total FROM jobs WHERE status NOT IN ('completed','cancelled')`).first(),
  ]);
  const total=Number(totalRow?.total||0);
  return json({jobs:rows.results||[],page,pageSize:limit,total,totalPages:Math.ceil(total/limit),activeTotal:Number(activeRow?.total||0)});
}
export async function onRequestPost(context){const{env,request}=context;await ensureSchema(env.QUOTES_DB);let body;try{body=await request.json();}catch{return json({error:'Invalid JSON.'},400);}
  if(body&&body.workType==='general'){
    const checked=validateNewGeneralJob(body);if(checked.errors)return json({error:checked.errors[0],errors:checked.errors},400);
    const v=checked.value;
    // A double tap on Save must not create two jobs.
    const twin=await env.QUOTES_DB.prepare(`SELECT id FROM jobs WHERE work_type='general' AND customer_name=? AND work_description=? AND agreed_cents=? AND created_at>?`).bind(v.customer_name,v.work_description,v.agreed_cents,new Date(Date.now()-120000).toISOString()).first();
    if(twin)return json({id:twin.id,existing:true,workType:'general'},200);
    const now=new Date().toISOString(),id=makeId();
    await env.QUOTES_DB.prepare(`INSERT INTO jobs (id,created_at,updated_at,quote_id,status,scheduled_date,scheduled_window,customer_name,customer_phone,customer_email,customer_address,customer_city,notes,created_by,work_type,work_description,agreed_cents,contract_date) VALUES (?,?,?,NULL,?,?,?,?,?,?,?,?,?,'mark','general',?,?,?)`).bind(id,now,now,v.status,v.scheduled_date,v.scheduled_window,v.customer_name,v.customer_phone??null,v.customer_email??null,v.customer_address??null,v.customer_city??null,v.notes,v.work_description,v.agreed_cents,v.contract_date).run();
    return json({id,created:true,workType:'general'},201);
  }
  const quoteId=typeof body.quoteId==='string'?body.quoteId.trim():'';if(!quoteId)return json({error:'A finalized quote is required.'},400);const quote=await env.QUOTES_DB.prepare(`SELECT * FROM quotes WHERE id = ?`).bind(quoteId).first();if(!quote)return json({error:'Quote not found.'},404);if(quote.status!=='finalized')return json({error:'Only finalized quotes can become jobs.'},409);const existing=await env.QUOTES_DB.prepare(`SELECT id FROM jobs WHERE quote_id = ?`).bind(quoteId).first();if(existing)return json({id:existing.id,existing:true},200);const validated=await validatedApprovedPlan(env.QUOTES_DB,quoteId);if(validated.error)return json(validated,validated.status||409);const{plan,planVersion,knowledgeVersion,savedPlanRow}=validated;const now=new Date().toISOString(),id=makeId();plan.finalizedSnapshot=true;plan.finalizedAt=now;plan.approvedAt=savedPlanRow.approved_at||plan.approvedAt||null;plan.approvedBy=savedPlanRow.approved_by||plan.approvedBy||null;await env.QUOTES_DB.prepare(`INSERT INTO jobs (id,created_at,updated_at,quote_id,status,customer_name,customer_phone,customer_email,customer_address,customer_city,notes,build_plan_json,build_plan_version,build_plan_knowledge_version,build_plan_attached_at,build_plan_attached_by,created_by) VALUES (?,?,?,?,'ready',?,?,?,?,?,?,?,?,?,?,?,'mark')`).bind(id,now,now,quoteId,quote.customer_name,quote.customer_phone||null,quote.customer_email||null,quote.customer_address||null,quote.customer_city||null,quote.notes||null,JSON.stringify(plan).slice(0,150000),planVersion,knowledgeVersion,now,'mark').run();await env.QUOTES_DB.prepare(`INSERT INTO job_build_plan_events (job_id,quote_id,plan_version,knowledge_version,event_type,created_at,created_by,notes) VALUES (?,?,?,?,?,?,?,?)`).bind(id,quoteId,planVersion,knowledgeVersion,'created',now,'mark','Approved Build Plan attached during job creation.').run();return json({id,created:true,buildPlanVersion:planVersion,buildPlanKnowledgeVersion:knowledgeVersion},201);}
export async function onRequestPatch(context){const{env,request}=context;await ensureSchema(env.QUOTES_DB);const id=new URL(context.request.url).searchParams.get('id');if(!id)return json({error:'Job id is required.'},400);let body;try{body=await request.json();}catch{return json({error:'Invalid JSON.'},400);}const job=await env.QUOTES_DB.prepare(`SELECT * FROM jobs WHERE id = ?`).bind(id).first();if(!job)return json({error:'Job not found.'},404);
  const general=isGeneralJob(job);let generalUpdate=null;
  if(general){const c=validateGeneralJobUpdate(body);if(c.errors)return json({error:c.errors[0],errors:c.errors},400);generalUpdate=c.value;
    if(generalUpdate.agreed_cents!==undefined){let paid=0;try{paid=Number((await env.QUOTES_DB.prepare(`SELECT amount_paid_cents FROM job_payments WHERE job_id=?`).bind(id).first())?.amount_paid_cents)||0;}catch{}if(generalUpdate.agreed_cents<paid)return json({error:'The agreed amount cannot be less than what has already been recorded as paid. Correct the payment record first.',code:'AGREED_BELOW_PAID'},409);}}
  if(body.action==='reconcileBuildPlan'){
    if(general)return json({error:'General jobs have no Build Plan.',code:'GENERAL_JOB'},409);
    if(job.status==='cancelled')return json({error:'Cancelled jobs are historical records and are not eligible for Build Plan reconciliation.',code:'JOB_CANCELLED'},409);
    if(job.build_plan_json)return json({error:'This job already has a Build Plan snapshot.',code:'BUILD_PLAN_SNAPSHOT_EXISTS'},409);
    if(!job.quote_id)return json({error:'This job is not linked to a quote.',code:'QUOTE_REQUIRED'},409);
    const validated=await validatedApprovedPlan(env.QUOTES_DB,job.quote_id);if(validated.error)return json(validated,validated.status||409);
    const now=new Date().toISOString(),plan={...validated.plan,finalizedSnapshot:true,finalizedAt:now,approvedAt:validated.savedPlanRow.approved_at||validated.plan.approvedAt||null,approvedBy:validated.savedPlanRow.approved_by||validated.plan.approvedBy||null};
    await env.QUOTES_DB.prepare(`UPDATE jobs SET updated_at=?,build_plan_json=?,build_plan_version=?,build_plan_knowledge_version=?,build_plan_attached_at=?,build_plan_attached_by=? WHERE id=?`).bind(now,JSON.stringify(plan).slice(0,150000),validated.planVersion,validated.knowledgeVersion,now,'mark',id).run();
    await env.QUOTES_DB.prepare(`INSERT INTO job_build_plan_events (job_id,quote_id,plan_version,knowledge_version,event_type,created_at,created_by,notes) VALUES (?,?,?,?,?,?,?,?)`).bind(id,job.quote_id,validated.planVersion,validated.knowledgeVersion,'reconciled',now,'mark','Explicitly attached current approved Build Plan to a legacy job.').run();
    return json({ok:true,reconciled:true,buildPlanVersion:validated.planVersion,buildPlanKnowledgeVersion:validated.knowledgeVersion,buildPlanAttachedAt:now});
  }
  const allowedStatuses=new Set(['ready','scheduled','in-progress','completed','cancelled']);const status=typeof body.status==='string'&&allowedStatuses.has(body.status)?body.status:job.status;let scheduledDate=job.scheduled_date;if(typeof body.scheduledDate==='string'){const d=body.scheduledDate.trim();if(d){const t=new Date(`${d}T00:00:00Z`);if(!/^\d{4}-\d{2}-\d{2}$/.test(d)||Number.isNaN(t.getTime())||t.toISOString().slice(0,10)!==d)return json({error:'Scheduled date must be a real date (YYYY-MM-DD).'},400);scheduledDate=d;}else scheduledDate=null;}const scheduledWindow=typeof body.scheduledWindow==='string'?body.scheduledWindow.trim().slice(0,120)||null:job.scheduled_window;const notes=typeof body.notes==='string'?body.notes.slice(0,8000):job.notes;const installNotes=typeof body.installNotes==='string'?body.installNotes.slice(0,8000):job.install_notes;let closeoutNotes=typeof body.closeoutNotes==='string'?body.closeoutNotes.slice(0,8000):job.closeout_notes;if(status==='completed'&&!general){const progress=await checklistProgress(env.QUOTES_DB,id);if(!progress.total||progress.done<progress.total)return json({error:`Complete the field checklist before closing this job (${progress.done} of ${progress.total} complete).`,code:'CLOSEOUT_CHECKLIST_INCOMPLETE',completed:progress.done,total:progress.total},409);const finalized=await env.QUOTES_DB.prepare(`SELECT finalized_at, signoff_notes FROM job_closeouts WHERE job_id=?`).bind(id).first();if(!finalized?.finalized_at)return json({error:'Finalize the dedicated project closeout before marking this job completed.',code:'CLOSEOUT_FINALIZATION_REQUIRED'},409);if(!String(closeoutNotes||'').trim()&&String(finalized.signoff_notes||'').trim())closeoutNotes=String(finalized.signoff_notes).slice(0,8000);}const now=new Date().toISOString(),completedAt=status==='completed'?(job.completed_at||now):null;await env.QUOTES_DB.prepare(`UPDATE jobs SET updated_at=?,status=?,scheduled_date=?,scheduled_window=?,notes=?,install_notes=?,closeout_notes=?,completed_at=? WHERE id=?`).bind(now,status,scheduledDate,scheduledWindow,notes,installNotes,closeoutNotes,completedAt,id).run();if(generalUpdate&&Object.keys(generalUpdate).length){const cols=Object.keys(generalUpdate);await env.QUOTES_DB.prepare(`UPDATE jobs SET ${cols.map((c)=>`${c}=?`).join(',')} WHERE id=?`).bind(...cols.map((c)=>generalUpdate[c]),id).run();}return json({ok:true,checklist:await checklistProgress(env.QUOTES_DB,id)});}
