import assert from 'node:assert/strict';
import { normalizeIntent, intentSummary } from '../functions/_lib/intent.mjs';
import { onRequestPost } from '../functions/api/estimate.js';
import { onRequestGet } from '../functions/internal/api/leads.js';
import { createD1 } from './_lib/d1-sqlite.mjs';
const now = Date.now();
const raw = { startedAt: now - 1000, sessions: 3, counts: { calculator_start: 2000, calculator_result: 1, return_visit: 2, estimate_form_start: 1, email_address: 'private@example.com', arbitrary: 1 } };
const normalized = normalizeIntent(raw);
assert.equal(normalized.counts.calculator_start, 100);
assert.equal(normalized.counts.email_address, undefined);
assert.equal(normalizeIntent({ ...raw, startedAt: now - 91 * 86400000 }), null);
assert.equal(normalizeIntent({ ...raw, startedAt: now + 120000 }), null);
assert.equal(intentSummary(raw).score, 50);
const db = createD1({ schemaFiles: ['functions/api/_data/schema.sql'] });
const form = new FormData();
for (const [key, value] of Object.entries({ name: 'Test Lead', phone: '3605550100', city: 'Camas', visit_journey: JSON.stringify({ visits: [{ path: '/tools/window-cost' }], intent: raw }) })) form.set(key, value);
const pending = [];
const request = new Request('https://windowsbyclearview.com/api/estimate', { method: 'POST', headers: { accept: 'application/json', origin: 'https://windowsbyclearview.com' }, body: form });
const originalFetch = globalThis.fetch;
globalThis.fetch = async () => new Response('{"id":"test"}');
const response = await onRequestPost({ request, env: { QUOTES_DB: db, RESEND_API_KEY: 'test' }, waitUntil: p => pending.push(p) });
await Promise.all(pending);
globalThis.fetch = originalFetch;
assert.equal(response.status, 200);
const row = db.raw.prepare('SELECT * FROM leads').get();
assert.deepEqual(JSON.parse(row.intent_json), normalized);
const listing = await onRequestGet({ env: { QUOTES_DB: db } });
const lead = (await listing.json()).leads[0];
assert.equal(lead.intent.sessions, 3);
assert.equal(lead.intent.score, 50);
assert.ok(lead.intent.signals.includes('Built a calculator result'));
assert.ok(!JSON.stringify(lead.intent).includes('private@example.com'));
assert.equal(intentSummary(normalized, now).score, 50);
assert.equal(intentSummary(normalized, now + 100 * 86400000), null);
console.log('PASS: bounded allowlisted intent persists through the real estimate handler and authenticated lead report; expiry and field exclusion verified.');
